// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type iolatIolatStart struct {
	_       structs.HostLayout
	Ts      uint64
	PidTgid uint64
	Comm    [16]int8
}

// loadIolat returns the embedded CollectionSpec for iolat.
func loadIolat() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_IolatBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load iolat: %w", err)
	}

	return spec, err
}

// loadIolatObjects loads iolat and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*iolatObjects
//	*iolatPrograms
//	*iolatMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadIolatObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadIolat()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// iolatSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type iolatSpecs struct {
	iolatProgramSpecs
	iolatMapSpecs
	iolatVariableSpecs
}

// iolatProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type iolatProgramSpecs struct {
	IolatComplete *ebpf.ProgramSpec `ebpf:"iolat_complete"`
	IolatIssue    *ebpf.ProgramSpec `ebpf:"iolat_issue"`
}

// iolatMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type iolatMapSpecs struct {
	Hist    *ebpf.MapSpec `ebpf:"hist"`
	StartTs *ebpf.MapSpec `ebpf:"start_ts"`
}

// iolatVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type iolatVariableSpecs struct {
}

// iolatObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadIolatObjects or ebpf.CollectionSpec.LoadAndAssign.
type iolatObjects struct {
	iolatPrograms
	iolatMaps
	iolatVariables
}

func (o *iolatObjects) Close() error {
	return _IolatClose(
		&o.iolatPrograms,
		&o.iolatMaps,
	)
}

// iolatMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadIolatObjects or ebpf.CollectionSpec.LoadAndAssign.
type iolatMaps struct {
	Hist    *ebpf.Map `ebpf:"hist"`
	StartTs *ebpf.Map `ebpf:"start_ts"`
}

func (m *iolatMaps) Close() error {
	return _IolatClose(
		m.Hist,
		m.StartTs,
	)
}

// iolatVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadIolatObjects or ebpf.CollectionSpec.LoadAndAssign.
type iolatVariables struct {
}

// iolatPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadIolatObjects or ebpf.CollectionSpec.LoadAndAssign.
type iolatPrograms struct {
	IolatComplete *ebpf.Program `ebpf:"iolat_complete"`
	IolatIssue    *ebpf.Program `ebpf:"iolat_issue"`
}

func (p *iolatPrograms) Close() error {
	return _IolatClose(
		p.IolatComplete,
		p.IolatIssue,
	)
}

func _IolatClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed iolat_bpfeb.o
var _IolatBytes []byte
